const express=require('express')
const verifyUser = require('../Middlewares/VerifyUser')
const { createPlaylist, getMyPlaylists, addToPlaylist, getPlaylist, deletePlaylist, updatePlaylist } = require('../Controllers/PlaylistController')
const { verify } = require('jsonwebtoken')
let playlistRouter=express.Router()
playlistRouter.post("/create",verifyUser,createPlaylist)
playlistRouter.get("/my-playlists",verifyUser,getMyPlaylists)
playlistRouter.post("/add-to-playlist",verifyUser,addToPlaylist)
playlistRouter.get("/playlist/:playlistId",verifyUser,getPlaylist)
playlistRouter.delete("/delete-playlist/:playlistId",verifyUser,deletePlaylist)
playlistRouter.put("/update-playlist/:playlistId",verifyUser,updatePlaylist)
module.exports=playlistRouter