const express=require('express')
const { createAccount, updatedUser, login, getProfile, getUser, follow, getDashboardStatistics, getAnalytics, getProfileBasicInfo, updateProfile, changePassword } = require('../Controllers/UserController')
const verifyUser = require('../Middlewares/VerifyUser')
let userRouter=express.Router()
userRouter.post("/createaccount",createAccount)
userRouter.post("/updateuser/:UID",updatedUser )
userRouter.post("/login",login )
userRouter.get("/getprofile/:id",getProfile )
userRouter.get("/getprofile-basicinfo",verifyUser,getProfileBasicInfo )
userRouter.put("/update-profile",verifyUser,updateProfile)
userRouter.put("/change-password",verifyUser,changePassword)
userRouter.post("/follow",verifyUser,follow )
userRouter.get("/get-dashboardstatistics",verifyUser,getDashboardStatistics)
userRouter.get("/get-analytics",verifyUser,getAnalytics)
module.exports=userRouter