const express=require('express')
const { createAccount, updatedUser, login, getProfile, getUser, follow } = require('../Controllers/UserController')
let userRouter=express.Router()
userRouter.post("/createaccount",createAccount)
userRouter.post("/updateuser/:UID",updatedUser )
userRouter.post("/login",login )
userRouter.get("/getprofile/:UID",getProfile )
userRouter.get("/getuser/:UID",getUser )
userRouter.post("/follow/:UID/:userToFollowID",follow )
module.exports=userRouter