const express=require('express')
const { getLikedVideos, getVideo, getSavedVideos, getWatchedVideos, addVideo, likeVideo, addComment, updateVideo, getVideoDetail, deleteVideo, deleteComment, saveVideo, getAllVideos } = require('../Controllers/VideoController')
const verifyUser = require('../Middlewares/VerifyUser')
const videoRouter=express.Router()
videoRouter.get("/get-allvideos",getAllVideos )
videoRouter.get("/getvideo/:videoId",getVideo )
videoRouter.get("/getlikedvideos/:UID", getLikedVideos)
videoRouter.get("/getsavedvideos/:UID",getSavedVideos )
videoRouter.get("/getwatchedvideos/:UID",getWatchedVideos )
videoRouter.post("/upload-video",verifyUser,addVideo )
videoRouter.post("/like/:ID/:UID",likeVideo )
videoRouter.post("/addcomment/:ID/:UID",addComment )
videoRouter.post("/updatevideo/:ID",updateVideo)
videoRouter.get("/getvideo/:ID",getVideoDetail)
videoRouter.delete("/deletevideo/:ID",deleteVideo)
videoRouter.post("/deletecomment/:ID/:commentID",deleteComment)
videoRouter.post("/save/:ID/:UID",saveVideo )
module.exports=videoRouter