const express=require('express')
const { getLikedVideos, getVideo, getSavedVideos, getWatchedVideos, addVideo, likeVideo, addComment, updateVideo, getVideoDetail, deleteVideo, deleteComment, saveVideo, getAllVideos, replyToComment } = require('../Controllers/VideoController')
const verifyUser = require('../Middlewares/VerifyUser')
const videoRouter=express.Router()
videoRouter.get("/get-allvideos",getAllVideos )
videoRouter.get("/getvideo/:videoId",getVideo )
videoRouter.get("/getlikedvideos/:UID", getLikedVideos)
videoRouter.get("/getsavedvideos/:UID",getSavedVideos )
videoRouter.get("/getwatchedvideos/:UID",getWatchedVideos )
videoRouter.post("/upload-video",verifyUser,addVideo )
videoRouter.post("/likevideo",verifyUser, likeVideo )
videoRouter.post("/addcomment/",verifyUser,addComment )
videoRouter.post("/replytocomment",verifyUser,replyToComment)
videoRouter.post("/updatevideo/:ID",updateVideo)
videoRouter.get("/getvideo/:ID",getVideoDetail)
videoRouter.delete("/deletevideo/:ID",deleteVideo)
videoRouter.post("/deletecomment/:ID/:commentID",deleteComment)
videoRouter.post("/save/:ID/:UID",saveVideo )
module.exports=videoRouter