const express=require('express')
const { getLikedVideos, getVideo, getSavedVideos, getWatchedVideos, addVideo, likeVideo, addComment, updateVideo, getVideoDetail, deleteVideo, saveVideo, getAllVideos, replyToComment, getSearchResults, getMyVideos, deleteWatchHistory } = require('../Controllers/VideoController')
const verifyUser = require('../Middlewares/VerifyUser')
const videoRouter=express.Router()
videoRouter.get("/get-allvideos",getAllVideos )
videoRouter.get("/getvideo/:videoId",getVideo )
videoRouter.get("/get-myvideos",verifyUser,getMyVideos)
videoRouter.delete("/delete-video/:videoId",verifyUser,deleteVideo)
videoRouter.put("/update-video",verifyUser,updateVideo)
videoRouter.get("/get-liked-videos",verifyUser, getLikedVideos)
videoRouter.get("/get-saved-videos",verifyUser,getSavedVideos )
videoRouter.get("/get-watched-videos",verifyUser, getWatchedVideos )
videoRouter.delete("/delete-watch-history",verifyUser,deleteWatchHistory)
videoRouter.post("/upload-video",verifyUser,addVideo )
videoRouter.post("/likevideo",verifyUser, likeVideo )
videoRouter.post("/addcomment/",verifyUser,addComment )
videoRouter.post("/replytocomment",verifyUser,replyToComment)
videoRouter.post("/search",getSearchResults)
videoRouter.post("/updatevideo/:ID",updateVideo)
videoRouter.get("/getvideo/:ID",getVideoDetail)
module.exports=videoRouter